### ISSUE TITLE
"pio returned non-zero exit status 1"

### ISSUE THREAD

**Issue by NotAFile** [coddingtonbear/neomake-platformio#2]
I am getting this error, but I am unable to copy it since the dialog instantly disappears.

This is on a pretty fresh install of the current version of Debian, Plugin is installed with `dein.vim`

When I try the same command on the terminal it works just fine.
![nvimerror](https://user-images.githubusercontent.com/5447747/29754947-106ffecc-8b90-11e7-8bd2-141a146c10a4.png)

**Comment by coddingtonbear** [comment]
*Usually* that means that you just haven't ran

```
call SetupPlatformioEnvironment('/path/to/your/platformio/project/')
```

Is it possible that you might have missed that instruction in the readme?

**Comment by NotAFile** [comment]
That command is what caused the above error.

**Comment by coddingtonbear** [comment]
In that case, I'm afraid I have no direct insight to give you except that -- given that the command executes properly in your shell, but not from within vim -- that the environment in which vim is executing the command differs in some fundamental way.

You might be able to glean a little more information by altering this line: https://github.com/coddingtonbear/neomake-platformio/blob/master/rplugin/python/neomake-platformio.py#L23 to something like (untested):

```python
proc = subprocess.Popen(
    [
        'pio',
        '-f',
        '-c',
        'vim',
        'run',
        '-t',
        'idedata',
        '-d',
        path,
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)
_, stderr = proc.communicate()
raise Exception(stderr)
```

Making those changes will cause the actual error message to be reported to you as the reason the command failed.

**Comment by NotAFile** [comment]
Interesting, it seems I didn't have a trailing `/` in my folder name. Perhaps "this is not a platformIO project" could be displayed a little more prettily.

The command runs without an error, but Neomake still does not recognize the platform libraries ("undeclared identifier" galore) so it might not actually be working though.

**Comment by coddingtonbear** [comment]
If you post a pull request for updating the output to be friendlier, I'd totally merge it.  Actually -- if you want to *own* this project, I'd gladly transfer it to you: against ten or so years of inertia, I switched from vim to vscode a couple months back.

**Comment by NotAFile** [comment]
A transfer would mean breaking all existing Links, right?

I don't think I'll be doing much work on this either, only thing I could do is answer issues. Platformio has a fork of this project, perhaps they would be interested in ownership?

**Comment by coddingtonbear** [comment]
Interestingly enough -- links aren't broken when transferring github repositories (with [some caveats](https://help.github.com/articles/about-repository-transfers/)), but I understand not wanting to take on that responsibility, anyway!
