### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [coddingtonbear/neomake-platformio#5]
Hello!

I found this project from the list "Recommended bundles" in https://docs.platformio.org/en/latest//integration/ide/vim.html .

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by coddingtonbear** [comment]
Ooo; I'm a little surprised nobody has commented on the missing license before.  Thanks for the heads-up; I've just added the MIT license to this project.

**Comment by vazhnov** [comment]
@coddingtonbear , Thank you!
